services:
  db:
    image: postgres:16
    container_name: sportsbook_db
    restart: always

    environment:
      POSTGRES_USER: mando
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: sportsbook

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: